export { default as About } from './about.astro';
export { default as Contact } from './contact.astro';
export { default as CoreExpertise } from './core-expertise.astro';
export { default as Footer } from './footer.astro';
export { default as Header } from './header.astro';
export { default as Hero } from './hero.astro';
export { default as ProfessionalExperience } from './professional-experience.astro';
export { default as SelectedWork } from './selected-work.astro';
export { default as Steps } from './steps.astro';
